Allow resizing without recreate
obsproject/obs-browser pull request #346
Opened 2022-01-15 09:34 UTC by exeldro

### Description
Allow resizing without recreate
![ezgif-3-63686cee83](https://user-images.githubusercontent.com/5457024/149616977-ef1a1e2b-c8cc-4b14-a162-b212e901a04a.gif)

### Motivation and Context
Resizing a browser source should not destroy and recreate it
This allows animating the size of the browser source.

### How Has This Been Tested?
On windows 64 bit using move value filters

### Types of changes
- New feature (non-breaking change which adds functionality) 

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-01-15 10:51 UTC, WizardCM commented
Ah, this works better than my implementation. I'm going to merge this PR after 27.2 as I'd like to make *all* the properties work without recreating the source. I already have CSS updating & URL changes working much better. The rest are a little trickier.

2022-01-15 23:55 UTC, WizardCM requested changes

2022-01-15 23:55 UTC, WizardCM commented on obs-browser-source.cpp
> +				return;
```suggestion
				return;
				
```

2022-01-15 23:55 UTC, WizardCM commented on obs-browser-source.cpp
> +				if (!cefBrowser)
Based on #325 this should use `GetBrowser()`.

2022-01-16 00:12 UTC, exeldro commented
now using `ExecuteOnBrowser` instead of `QueueCEFTask`

2022-01-18 11:55 UTC, merged