Add support for more events
obsproject/obs-browser pull request #363
Opened 2022-05-27 00:12 UTC by kevmo314

### Description
This change adds support for obsSceneListChanged, obsTransitionChanged,
obsTransitionListChanged events. The event arguments match the signatures
of the corresponding getters.

### Motivation and Context
Adds additional events for which there are corresponding getters already.

### How Has This Been Tested?
Compiled and manually tested.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2022-05-27 00:22 UTC, gxalpha requested changes
I'm just curious, what's the underlying motivation besides this? What issue does this solve? Not that I'm against this, I'd just love to know.

Fyi, your PR is from your master branch - don't worry about that for now, but in the future please make sure to use a non-master branch if possible.

Also see the note below.

2022-05-27 00:22 UTC, gxalpha commented on obs-browser-plugin.cpp
> +		obs_source_release(source);
Use `OBSSourceAutoRelease` here instead

2023-10-15 00:06 UTC, tt2468 approved these changes

2023-10-15 00:09 UTC, tt2468 requested changes
Do you mind rebasing this PR to current? Since the submission of this PR, we've moved to nlohmann JSON, so some code will require updating.

2023-11-07 07:26 UTC, Lain-B commented
Fixed json, manually merging.

2023-11-07 07:26 UTC, closed without merging