More js
obsproject/obs-browser pull request #410
Opened 2023-06-06 09:01 UTC by yuriy-chumak

### Description
1. Now the client code can change the startup script during execution
1. made "executeJavaScript()" function public

### Motivation and Context
* Startup script is autorun every URL change/reload, so we need the change to update it without re-creating the browser,
* We need the ability to run js code from a client app.

This changes are part of main obs-studio PR (I'll add the number).

### How Has This Been Tested?
Tested manually as part of other PR (I'll add the number).
* Windows 10 x64, Linux Ubuntu 22.04, macOS M1 Ventura, macOS x86_64 Catalina.

These changes should not affect existing code
 * except possible bug with changing startup script during execution, but I haven't seen such one in bug tracker.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

2023-06-07 20:26 UTC, RytoEX requested changes
Please provide a more descriptive PR title and commit message. Do not use merge commits.

2023-06-12 17:41 UTC, yuriy-chumak commented
@RytoEX,
done.

2023-06-12 17:51 UTC, RytoEX commented
> @RytoEX, done.

Per the [obs-studio contributing guidelines](https://github.com/obsproject/obs-studio/blob/cb391a595d45aea0d710680c143eb90efe22998b/CONTRIBUTING.rst), please use a verb for the first word of the PR title and commit message subject. Please make sure that both the PR title _and_ the commit message subject are updated. Preferably, avoid using a word like "better" to describe functions.

2023-06-14 20:10 UTC, yuriy-chumak commented
Updated.

2023-07-11 00:16 UTC, merged