Add hardware accel support under Linux
obsproject/obs-browser pull request #453
Opened 2024-09-11 12:11 UTC by tytan652

### Description

Requires:
- https://github.com/obsproject/obs-studio/pull/11219
- *placeholder for BrowserHWAccel config PR*

Add hwaccel support on Linux with CEF 6533 and later

### Motivation and Context

Just wanted to try to make it somehow work for fun, ended up making it for real…

### How Has This Been Tested?

Tested under Wayland and X11.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

2024-09-12 01:37 UTC, kkartaltepe commented on browser-client.cpp
> +		modifier = DRM_FORMAT_MOD_NONE;
Do not use the deprecated name MOD_NONE, use MOD_LINEAR.

2024-10-18 01:24 UTC, kkartaltepe approved these changes
Seems fine overall, i really wish we could pin down the modifier issue on x11 to something in cef's codebase... at least then we could see if it ever got fixed in the future.

2024-10-20 03:29 UTC, kkartaltepe commented
Doesnt compile with `ENABLE_BROWSER_SHARED_TEXTURE` set to 0 because this is used to avoid compiling the drm-formats stuff, but they are still referenced. Just remove the conditionals and always build these functions.

2024-10-20 04:02 UTC, kkartaltepe commented
Maybe i'm missing something on how this was tested, but current master sets the BrowserHwaccel option to false so nothing here takes effect until https://github.com/obsproject/obs-studio/blob/master/UI/obs-app.cpp#L1268-L1278 is flipped.

2024-10-20 04:15 UTC, kkartaltepe commented
https://gist.github.com/kkartaltepe/ebf66527a38f188c8b07eb43b2d37de6 I dont remember if this happened as well on my original test months ago. But on my steamdeck tier setup there is significant rendering performance loss so rendering is twice as slow for a scene with 10 browser sources.

2024-10-20 06:42 UTC, tytan652 commented
> Doesnt compile with `ENABLE_BROWSER_SHARED_TEXTURE` set to 0 because this is used to avoid compiling the drm-formats stuff, but they are still referenced. Just remove the conditionals and always build these functions.

`#if ENABLE_BROWSER_SHARED_TEXTURE` should have been `#ifdef ENABLE_BROWSER_SHARED_TEXTURE`, I fixed it.
Our relies on whether it's define or not, not its value.

> I dont remember if this happened as well on my original test months ago. But on my steamdeck tier setup there is significant rendering performance loss so rendering is twice as slow for a scene with 10 browser sources.

This is why we test, I don't know I would be able to reproduce…

2024-10-27 16:38 UTC, tytan652 commented
Changes:
- Avoid linking libdrm but expose it's include directory since we only need `DRM_FORMAT_`
- Blacklist NVIDIA driver since it does not work well on both Wayland and X11

2025-01-05 02:40 UTC, fatalgoth commented
Just streamed for six hours with these patches, minus the NVIDIA blacklisting and it solved some framedrops when certain browser overlays would draw to the screen for me. Instead of a blacklist, can it be a warning or something? It worked really well for me.

2025-01-23 20:02 UTC, RytoEX requested changes

2025-01-23 20:02 UTC, RytoEX commented on browser-client.cpp
> +#elif defined(__APPLE__) && defined(_WIN32)
How would both `__APPLE__` and `_WIN32` be defined? Was this meant to be inverted?
```cpp
#elif !defined(__APPLE__) && !defined(_WIN32)
```

2025-01-23 20:02 UTC, RytoEX commented on browser-client.cpp
> +#elif defined(__WIN32)
```suggestion
#elif defined(_WIN32)
```

2025-01-24 06:44 UTC, tytan652 commented on obs-browser-plugin.cpp
> +			       "acceleration.");
It was based on Windows `check_hwaccel_support`, but I did put the string as one piece in the new push.

2025-01-24 06:46 UTC, tytan652 commented on browser-client.cpp
> +#elif defined(__APPLE__) && defined(_WIN32)
Old shared_texture code path only meant for Windows and macOS, so `&&` should have been `||`. Fixed.

2025-01-24 06:57 UTC, tytan652 commented on drm-format.cpp
> +#define N_SUPPORTED_FORMATS (sizeof(supported_formats) / sizeof(supported_formats[0]))
Converted to constexpr

2025-01-30 18:32 UTC, RytoEX commented
> https://gist.github.com/kkartaltepe/ebf66527a38f188c8b07eb43b2d37de6 I dont remember if this happened as well on my original test months ago. But on my steamdeck tier setup there is significant rendering performance loss so rendering is twice as slow for a scene with 10 browser sources.

@kkartaltepe If the original test was done with CEF 103 and the test in October was done with CEF 126/127, then could this be the issue with Qt message loop (https://github.com/obsproject/obs-studio/issues/11485 et al)? Or is it a separate issue?

Would still like to know if this is good enough to merge, or if there's something else we need to address first.

2025-01-30 18:44 UTC, GeorgesStavracas requested changes

2025-01-30 18:44 UTC, GeorgesStavracas commented on drm-format.hpp
> +bool obs_cef_all_drm_formats_supported();
I don't know if this is the same in C++, but in C this would have been:

```suggestion
bool obs_cef_all_drm_formats_supported(void);
```

2025-01-30 18:56 UTC, tytan652 commented on drm-format.hpp
> +bool obs_cef_all_drm_formats_supported();
Not controversial so I made the change.

2025-01-31 02:15 UTC, kkartaltepe approved these changes

2025-01-31 02:45 UTC, kkartaltepe commented
> > https://gist.github.com/kkartaltepe/ebf66527a38f188c8b07eb43b2d37de6 I dont remember if this happened as well on my original test months ago. But on my steamdeck tier setup there is significant rendering performance loss so rendering is twice as slow for a scene with 10 browser sources.
> 
> @kkartaltepe If the original test was done with CEF 103 and the test in October was done with CEF 126/127, then could this be the issue with Qt message loop ([obsproject/obs-studio#11485](https://github.com/obsproject/obs-studio/issues/11485) et al)? Or is it a separate issue?
> 
> Would still like to know if this is good enough to merge, or if there's something else we need to address first.

No I think its unrelated to that. When i profiled it, graphics stuff was just really slow.

2025-01-31 17:21 UTC, RytoEX approved these changes

2025-04-01 20:44 UTC, merged